// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_o4E3MnBFXcDp4THtJ28ana6KgmEAJGc',
    appId: '1:184878326025:web:b2c163c4fe13aabb0f73d8',
    messagingSenderId: '184878326025',
    projectId: 'chat-app-76ba0',
    authDomain: 'chat-app-76ba0.firebaseapp.com',
    storageBucket: 'chat-app-76ba0.appspot.com',
    measurementId: 'G-RHNXMV45HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhNumrYZy47HR-2kcETpXRthPdTACijFY',
    appId: '1:184878326025:android:bb0fb26e32f82b030f73d8',
    messagingSenderId: '184878326025',
    projectId: 'chat-app-76ba0',
    storageBucket: 'chat-app-76ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XG6ID6VQamdAqZJSnKhuc1uE31nQ44g',
    appId: '1:184878326025:ios:7ba3dbfb17eff1790f73d8',
    messagingSenderId: '184878326025',
    projectId: 'chat-app-76ba0',
    storageBucket: 'chat-app-76ba0.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XG6ID6VQamdAqZJSnKhuc1uE31nQ44g',
    appId: '1:184878326025:ios:d75fde74404c2fc60f73d8',
    messagingSenderId: '184878326025',
    projectId: 'chat-app-76ba0',
    storageBucket: 'chat-app-76ba0.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
